wordpress:
  image: wordpress
  links:
    - wordpress_db:mysql
  ports:
    - 8080:80
    #- "public_ip:80:80"
  volumes:
     - ./html:/var/www/html
     - ./plugins:/var/www/html/wp-content/plugins
#mariaDB
wordpress_db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: password
#phpmyadmin
phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - wordpress_db:mysql
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: password